### ISSUE TITLE
Update nuclear ramping/p_min_pu based on historical behavior

### ISSUE THREAD

**Issue by daniel-rdt** [open-energy-transition/form-energy-storage#35]
- See https://edf.hal.science/hal-01977209v1/document
- See https://www.nrel.gov/docs/fy20osti/77088.pdf

**Comment by virio-andreyana** [comment]
![grafik](https://github.com/user-attachments/assets/7ffe1c84-8e5c-4928-a5ef-62a39718624f)

Source: https://www.oecd-nea.org/jcms/pl_62445/technical-and-economic-aspects-of-load-following-with-nuclear-power-plants?details=true

This figure is a historical capacity factor of a nuclear power plant in France encompassing the entire nuclear fuel cycle. The start date is the instalment of a new fuel rod while the end date is the removal of those pellets. What's interesting is that in **the first two weeks and in the last 5-20%** of the nuclear fuel cycle lifetime, the nuclear power plant is unable to do load follow because of the properties of the nuclear pellets and potential corrosion.

So the 20% minimum load maybe valid ~70% of the time. 

I don't think we are able to capture this characteristic in our model. But it can give justification for higher minimum load if needed.
